using abort_signal::{ set_abort_callback }
using runtime_assert::{ assert }

test catch_abort_signal_and_exit_with_number_of_failures {
  stdin = ""
  stdout = ""
  exit = 4
}

thread_local usize mut fails = 0;

fn onabort() {
  fails++;
}

fn main() -> int {
  set_abort_callback(onabort);

  assert(false);
  assert(false);
  assert(false);
  assert(false);
  return as<int>(fails);
}
